backup k8s cluster

diff --git a/src/eks/tasks b/src/eks/tasks
--- a/src/eks/tasks
+++ b/src/eks/tasks
@@ -10,18 +10,20 @@ if [[ "${K8S_EXP_ENVIRONMENT}" != "testing" ]] && [[ "${K8S_EXP_ENVIRONMENT}" !=
 fi
 
 export K8S_EXP_CLUSTER_NAME="eks-${K8S_EXP_ENVIRONMENT}"
+export K8S_EXP_VELERO_S3_BUCKET="k8s-eks-for-masters-thesis.k8s.local"
 
 command="$1"
 case "${command}" in
     _create)
-    # ssh key? vpc? ip public?
-        set -x
         my_ip=$(curl https://ipinfo.io/ip 2>/dev/null)
         sed "s/\${K8S_EXP_CLUSTER_NAME}/${K8S_EXP_CLUSTER_NAME}/" cluster.tmpl.yaml > cluster1.yaml
         sed "s/\${K8S_EXP_REGION}/${K8S_EXP_REGION}/" cluster1.yaml > cluster2.yaml
         sed "s/\${K8S_EXP_ENVIRONMENT}/${K8S_EXP_ENVIRONMENT}/" cluster2.yaml > cluster3.yaml
         sed "s'\${my_ip}'${my_ip}/32'" cluster3.yaml > cluster.yaml
         rm cluster1.yaml cluster2.yaml cluster3.yaml
+        # print date, so that end user can expect how much longer to wait
+        date
+        set -x
         time eksctl create cluster -f cluster.yaml
         ;;
     _test)
@@ -30,7 +32,31 @@ case "${command}" in
         time bats tests.bats
         cd ../eks
         ;;
+    _install_velero_cli)
+        wget -O /tmp/velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.4.0/velero-v1.4.0-linux-amd64.tar.gz
+        cd /tmp
+        tar -xvf velero.tar.gz
+        chmod +x velero/velero
+        sudo mv velero/velero /usr/local/bin/velero
+        ;;
+    _enable_velero)
+        if aws s3api list-buckets | jq '.Buckets[]["Name"]' | grep ${K8S_EXP_VELERO_S3_BUCKET}; then
+          echo "Error: S3 Bucket: ${K8S_EXP_VELERO_S3_BUCKET} does not exist"
+          exit 1
+        fi
+        set -x
+        kubectl create namespace velero
+        helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
+        helm install velero --namespace velero -f ${PWD}/../velero/velero-chart-values.yaml \
+          --set configuration.backupStorageLocation.bucket=${K8S_EXP_VELERO_S3_BUCKET} \
+          --set configuration.backupStorageLocation.prefix=${K8S_EXP_ENVIRONMENT} \
+          --set configuration.backupStorageLocation.config.region=${K8S_EXP_REGION} \
+          --set-file credentials.secretContents.cloud=credentials-velero \
+          --wait --atomic vmware-tanzu/velero
+        ;;
     _delete)
+        # print date, so that end user can expect how much longer to wait
+        date
         set -x
         time eksctl delete cluster -f cluster.yaml --wait
         ;;
diff --git a/src/kops/tasks b/src/kops/tasks
--- a/src/kops/tasks
+++ b/src/kops/tasks
@@ -10,6 +10,7 @@ export K8S_EXP_REGION="eu-west-1"
 # there will be 1 s3 bucket to keep k8s clusters config, for many clusters
 # (for many environments)
 export K8S_EXP_KOPS_S3_BUCKET="k8s-kops-for-masters-thesis.k8s.local"
+export K8S_EXP_VELERO_S3_BUCKET="${K8S_EXP_KOPS_S3_BUCKET}"
 
 if [[ "${K8S_EXP_ENVIRONMENT}" != "testing" ]] && [[ "${K8S_EXP_ENVIRONMENT}" != "production" ]]; then
   echo "Error: K8S_EXP_ENVIRONMENT should be set to testing or production"
@@ -62,18 +63,13 @@ case "${command}" in
         # kops toolbox template --name ${K8S_EXP_CLUSTER_NAME} --set environment=${K8S_EXP_ENVIRONMENT} --template cluster-ha.tmpl.yaml --format-yaml > cluster-ha-${K8S_EXP_ENVIRONMENT}.yaml
         # kops replace -f cluster-ha-${K8S_EXP_ENVIRONMENT}.yaml --name ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" --force
         ;;
-    _install_velero_cli)
-        wget -O /tmp/velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.4.0/velero-v1.4.0-linux-amd64.tar.gz
-        cd /tmp
-        tar -xvf velero.tar.gz
-        chmod +x velero/velero
-        sudo mv velero/velero /usr/local/bin/velero
-        ;;
     _create)
         # deploy the cluster; --force is needed if "kops create cluster" was not run before
         kops create secret --name ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" sshpublickey admin -i ~/.ssh/id_rsa.pub
         kops replace -f cluster-${K8S_EXP_ENVIRONMENT}.yaml --name ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" --force
         # kops replace -f cluster-ha-${K8S_EXP_ENVIRONMENT}.yaml --name ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" --force
+        # print date, so that end user can expect how much longer to wait
+        date
         kops update cluster ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" --yes
         # wait for the deployment to finish
         date
@@ -102,8 +98,30 @@ case "${command}" in
         ;;
     _enable_as)
         set -x
-        sed "s/\${CLUSTER_NAME}/${K8S_EXP_CLUSTER_NAME}/" ../as/cluster-autoscaler-autodiscover.tmpl.yaml > ../as/cluster-autoscaler-autodiscover.yaml
-        kubectl apply -f ../as/cluster-autoscaler-autodiscover.yaml
+        sed "s/\${CLUSTER_NAME}/${K8S_EXP_CLUSTER_NAME}/" ../as/cluster-autoscaler-autodiscover.tmpl.yaml > cluster-autoscaler-autodiscover.yaml
+        kubectl apply -f cluster-autoscaler-autodiscover.yaml
+        ;;
+    _install_velero_cli)
+        wget -O /tmp/velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.4.0/velero-v1.4.0-linux-amd64.tar.gz
+        cd /tmp
+        tar -xvf velero.tar.gz
+        chmod +x velero/velero
+        sudo mv velero/velero /usr/local/bin/velero
+        ;;
+    _enable_velero)
+        if aws s3api list-buckets | jq '.Buckets[]["Name"]' | grep ${K8S_EXP_VELERO_S3_BUCKET}; then
+          echo "Error: S3 Bucket: ${K8S_EXP_VELERO_S3_BUCKET} does not exist"
+          exit 1
+        fi
+        set -x
+        kubectl create namespace velero
+        helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
+        helm install velero --namespace velero -f ${PWD}/../velero/velero-chart-values.yaml \
+          --set configuration.backupStorageLocation.bucket=${K8S_EXP_VELERO_S3_BUCKET} \
+          --set configuration.backupStorageLocation.prefix=${K8S_EXP_ENVIRONMENT} \
+          --set configuration.backupStorageLocation.config.region=${K8S_EXP_REGION} \
+          --set-file credentials.secretContents.cloud=credentials-velero \
+          --wait --atomic vmware-tanzu/velero
         ;;
     _test)
         set -x
@@ -113,6 +131,8 @@ case "${command}" in
         cd ../kops
         ;;
     _delete)
+        # print date, so that end user can expect how much longer to wait
+        date
         set -x
         kops delete cluster --name ${K8S_EXP_CLUSTER_NAME} --state "s3://${K8S_EXP_KOPS_S3_BUCKET}" --yes
         aws logs delete-log-group --log-group-name k8s-kops-${K8S_EXP_ENVIRONMENT}
